# This is a configuration file for the Python application.

# It contains settings for security, connection, and debug mode.
SECURITY_KEY: 'django-insecure-change-me-to-a-secure-key'

# Connection configuration
DOMAIN: '127.0.0.1' # The domain or IP address the application will run on
PORT: '8000' # The port the application will listen on
PROTOCOL: 'http' # The protocol to use (http or https)

# Debug mode: set to True for development, False for production
DEBUG: True

# Database configuration
DB_ENGINE: 'django.db.backends.postgresql'
DB_NAME: 'scholarships'
DB_USER: 'scholarships_user'
DB_PASSWORD: 'scholarships_password'
DB_HOST: 'localhost'
DB_PORT: '5432'