# Generated by Django 5.2.3 on 2025-07-20 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("becas_sntsa", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="solicitud",
            name="estado",
            field=models.CharField(
                choices=[
                    ("R", "Solicitud recibida"),
                    ("E", "Error en documentos, revisar notas"),
                    ("P", "En espera de resultados"),
                    ("T", "Beca otorgada"),
                    ("F", "Beca no otorgada"),
                ],
                default="P",
                max_length=1,
            ),
        ),
    ]
