# Generated by Django 5.2.13 on 2026-07-12 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('becas_sntsa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='estado',
            field=models.CharField(choices=[('R', 'Solicitud recibida'), ('E', 'Error en documentos, revisar notas'), ('P', 'Solicitud recibida y en espera de sorteo'), ('T', 'Beca otorgada'), ('F', 'Beca no otorgada')], default='R', max_length=1),
        ),
    ]
