# Generated by Django 5.2.3 on 2025-06-29 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("becas_sntsa", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trabajador",
            name="aprobado",
            field=models.BooleanField(default=False),
        ),
    ]
