# Generated by Django 5.2.3 on 2025-07-20 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("becas_sntsa", "0002_alter_solicitud_estado"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="solicitud",
            constraint=models.UniqueConstraint(
                condition=models.Q(("estado", "P")),
                fields=("becario",),
                name="unique_solicitud_en_espera",
            ),
        ),
    ]
