# Generated by Django 5.2.3 on 2025-06-29 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("becas_sntsa", "0002_trabajador_aprobado"),
    ]

    operations = [
        migrations.CreateModel(
            name="SolicitudAprovechamiento",
            fields=[
                (
                    "solicitud_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="becas_sntsa.solicitud",
                    ),
                ),
                ("promedio", models.FloatField()),
                ("boleta", models.FileField(upload_to="boleta/")),
                (
                    "grado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="becas_sntsa.grado",
                    ),
                ),
            ],
            bases=("becas_sntsa.solicitud",),
        ),
        migrations.CreateModel(
            name="SolicitudExcelencia",
            fields=[
                (
                    "solicitud_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="becas_sntsa.solicitud",
                    ),
                ),
                ("promedio", models.FloatField()),
                ("boleta", models.FileField(upload_to="boleta/")),
                ("carrera", models.CharField(max_length=128)),
                (
                    "grado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="becas_sntsa.grado",
                    ),
                ),
            ],
            bases=("becas_sntsa.solicitud",),
        ),
        migrations.DeleteModel(
            name="SolicitudNormal",
        ),
    ]
