# Generated by Django 5.1.3 on 2025-01-27 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=4)),
                ('nombre', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='LugarAdscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(blank=True, max_length=32, null=True)),
                ('nombre', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Puesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateField(auto_now_add=True)),
                ('recibo_nomina', models.FileField(upload_to='recibo_nomina/')),
                ('ine', models.FileField(upload_to='ine/')),
            ],
        ),
        migrations.CreateModel(
            name='Becario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
                ('apellido_paterno', models.CharField(max_length=128)),
                ('apellido_materno', models.CharField(blank=True, max_length=128, null=True)),
                ('curp', models.CharField(max_length=18)),
                ('curp_archivo', models.FileField(upload_to='curp/')),
                ('sexo', models.CharField(max_length=1)),
                ('fecha_nacimiento', models.DateField()),
                ('acta_nacimiento', models.FileField(upload_to='acta_nacimiento/')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudEspecial',
            fields=[
                ('solicitud_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.solicitud')),
                ('diagnostico_medico', models.CharField(max_length=128)),
                ('tipo_educacion', models.CharField(max_length=128)),
                ('certificado_medico', models.FileField(upload_to='certificado_medico/')),
                ('certificado_escolar', models.FileField(upload_to='certificado_escolar/')),
                ('obtuvo_beca', models.BooleanField(blank=True, default=False, null=True)),
            ],
            bases=('main.solicitud',),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='becario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.becario'),
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
                ('apellido_paterno', models.CharField(max_length=128)),
                ('apellido_materno', models.CharField(blank=True, max_length=128, null=True)),
                ('curp_archivo', models.FileField(upload_to='curp/')),
                ('telefono', models.CharField(max_length=16)),
                ('correo', models.EmailField(max_length=254)),
                ('lugar_adscripcion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.lugaradscripcion')),
                ('puesto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.puesto')),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.seccion')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudNormal',
            fields=[
                ('solicitud_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.solicitud')),
                ('promedio', models.FloatField()),
                ('boleta', models.FileField(upload_to='boleta/')),
                ('obtuvo_beca', models.BooleanField(blank=True, default=False, null=True)),
                ('grado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.grado')),
            ],
            bases=('main.solicitud',),
        ),
    ]
