# Generated by Django 5.1.3 on 2025-01-30 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='becario',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='becario',
            name='sexo',
        ),
    ]
