# Generated by Django 5.1.5 on 2025-01-30 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_solicitudnormal_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudespecial',
            name='obtuvo_beca',
        ),
        migrations.RemoveField(
            model_name='solicitudnormal',
            name='obtuvo_beca',
        ),
        migrations.AddField(
            model_name='solicitud',
            name='obtuvo_beca',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='solicitudnormal',
            name='tipo',
            field=models.CharField(choices=[('A', 'Aprovechamiento'), ('E', 'Excelencia')], default='A', max_length=1),
        ),
    ]
